name: yedenradio
description: Open Source Volunteers project for noncommercial radio, Yeden Radio! You are not alone!

version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  url_audio_stream: ^1.0.0+3
  audio_service: ^0.5.7
  provider: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/logo.png